name: Golden CI

on:
  workflow_call:
    inputs:
      language:
        required: true
        type: string

jobs:
  ci:
    uses: org/templates/.github/workflows/ci/ci-base.yml@v1
    with:
      language: ${{ inputs.language }}

  sast:
    uses: org/templates/.github/workflows/security/security-sast.yml@v1
    with:
      languages: ${{ inputs.language }}

  secrets:
    uses: org/templates/.github/workflows/security/security-secrets.yml@v1
